<?php
/*
Ad Injection config file
DO NOT EDIT MANUALLY
This file is generated by Ad Injection
*/

function adinj_config_sevisitors_only() { return false; }
function adinj_config_search_engine_referrers() { return array('.google.', '.bing.', '.yahoo.', '.ask.', 'search?', 'search.'); }

function adinj_config_block_ips() { return false; }
function adinj_config_blocked_ips() { return array(); }

//TODO not yet implemented
function adinj_config_block_keywords() { return false; }
function adinj_config_blocked_keywords() { return array(); }

function adinj_config_debug_mode() { return false; }

// Don't use these - they will be deleted soon

function adinj_config_add_tags_rnd($ad) { return ""; }
function adinj_config_add_tags_top($ad) { return ""; }
function adinj_config_add_tags_bottom($ad) { return ""; }


?>